export const productVariants = [
  {
    category: "Car Parts",
    subCategories: [
      "Engine",
      "Side Mirror",
      "Windscreen / Windshield",
      "Headlights",
      "Tail Lights",
      "Bumper",
      "Fender",
      "Door Handle",
      "Brake Pads",
      "Brake Discs / Rotors",
      "Shock Absorbers",
      "Suspension Arms",
      "Radiator",
      "Alternator",
      "Battery",
      "Spark Plugs",
      "Oil Filter",
      "Air Filter",
      "Fuel Filter",
      "Clutch",
      "Gearbox / Transmission",
      "Drive Shaft",
      "Tyres / Wheels",
      "Wiper Blades",
      "Exhaust System",
      "Catalytic Converter",
      "AC Compressor",
      "Steering Rack",
      "Ball Joints",
      "Control Arms"
    ]
  },
  {
    category: "Phone Parts",
    subCategories: [
      "Display / Screen",
      "Touch Digitizer",
      "Battery",
      "Charging Port",
      "Motherboard / PCB",
      "Processor (SoC)",
      "Camera Module (Rear)",
      "Camera Module (Front)",
      "Speaker",
      "Earpiece",
      "Microphone",
      "Power Button",
      "Volume Buttons",
      "SIM Tray",
      "Back Cover / Housing",
      "Flex Cables",
      "Antenna",
      "Vibrator Motor",
      "Fingerprint Sensor",
      "Proximity Sensor",
      "Charging IC",
      "Power IC (PMIC)"
    ]
  },
  {
    category: "Laptop Parts",
    subCategories: [
      "Display Screen",
      "Keyboard",
      "Touchpad / Trackpad",
      "Battery",
      "Motherboard",
      "Processor (CPU)",
      "RAM",
      "SSD / Hard Drive",
      "Cooling Fan",
      "Heat Sink",
      "Hinges",
      "Palm Rest",
      "Power Jack / Charging Port",
      "Speakers",
      "Webcam",
      "Wi-Fi Card",
      "DC Power Adapter / Charger",
      "LCD Cable",
      "Bottom Case / Base Cover",
      "Top Cover / Lid"
    ]
  },
  {
    category: "Motorcycle Parts",
    subCategories: [
      "Engine",
      "Carburetor / Fuel Injector",
      "Exhaust Muffler",
      "Brake Pads",
      "Brake Disc",
      "Chain & Sprocket",
      "Clutch Plates",
      "Shock Absorbers",
      "Handlebar",
      "Side Mirror",
      "Headlight",
      "Tail Light",
      "Fuel Tank",
      "Seat",
      "Tyres",
      "Battery",
      "Spark Plug",
      "Air Filter"
    ]
  },
  {
    category: "Bicycle Parts",
    subCategories: [
      "Frame",
      "Fork",
      "Handlebar",
      "Stem",
      "Saddle / Seat",
      "Seat Post",
      "Wheels",
      "Tyres",
      "Tubes",
      "Brake Calipers",
      "Brake Pads",
      "Brake Levers",
      "Chain",
      "Cassette / Freewheel",
      "Crankset",
      "Pedals",
      "Derailleur (Front)",
      "Derailleur (Rear)",
      "Shifters",
      "Headset"
    ]
  }
];

const fuelTypes = [
  "Petrol / Gasoline",
  "Diesel",
  "Premium Petrol",
  "Regular Petrol",
  "Electric (EV)",
  "Hybrid (HEV)",
  "Plug-in Hybrid (PHEV)",
  "CNG (Compressed Natural Gas)",
  "LPG (Liquefied Petroleum Gas)",
  "Ethanol (E10, E15, E85)",
  "Biodiesel (B5, B20, B100)",
  "Hydrogen",
  "Methanol"
];